FROM webdevops/php-nginx:8.1-alpine

ENV WEB_DOCUMENT_ROOT=/app/public

WORKDIR /app

COPY composer* .

COPY . .

RUN chmod -R ug+w storage \
	&& chmod -R ug+w bootstrap/cache

RUN composer install --optimize-autoloader --no-dev

RUN php artisan optimize

RUN chown -R application:application .